/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Complaints */
        get: operations["list_complaints"];
        put?: never;
        /** Create Complaint */
        post: operations["create_complaint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Complaint */
        get: operations["get_complaint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Complaint Status */
        patch: operations["update_complaint_status"];
        trace?: never;
    };
    "/api/meta/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Providers */
        get: operations["get_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CacheStats */
        CacheStats: {
            /** Hit Rate */
            hit_rate: number;
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "water" | "electricity" | "sanitation" | "roads" | "streetlights" | "other";
        /** ComplaintCreate */
        ComplaintCreate: {
            /** Location */
            location: string;
            /** Reporter Contact */
            reporter_contact?: string | null;
            /** Text */
            text: string;
        };
        /** ComplaintOut */
        ComplaintOut: {
            /** Ai Summary */
            ai_summary: string | null;
            category: components["schemas"]["Category"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location */
            location: string;
            priority: components["schemas"]["Priority"];
            /** Reporter Contact */
            reporter_contact: string | null;
            status: components["schemas"]["Status"];
            /** Text */
            text: string;
            /** Triage Confidence */
            triage_confidence: number | null;
            /** Triage Latency Ms */
            triage_latency_ms: number;
            triaged_by: components["schemas"]["TriagedBy"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ComplaintPage */
        ComplaintPage: {
            /** Filters Applied */
            filters_applied: {
                [key: string]: string[];
            };
            /** Items */
            items: components["schemas"]["ComplaintOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
            /** Total */
            total: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Fields */
            fields?: components["schemas"]["FieldError"][] | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** FieldError */
        FieldError: {
            /** Code */
            code: string;
            /** Constraint */
            constraint?: {
                [key: string]: unknown;
            } | null;
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** HealthOut */
        HealthOut: {
            /** Pid */
            pid: number;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Version */
            version: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "high" | "normal" | "low";
        /** ProvidersOut */
        ProvidersOut: {
            active: components["schemas"]["TriagedBy"];
            /** Available */
            available: ("llm" | "ollama" | "rules" | "simulated")[];
            cache: components["schemas"]["CacheStats"];
            /**
             * Configured
             * @enum {string}
             */
            configured: "llm" | "ollama" | "rules" | "simulated";
            /** Recent */
            recent: components["schemas"]["TriageOutcome"][];
        };
        /** ReadyOut */
        ReadyOut: {
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** StatsOut */
        StatsOut: {
            /** By Category */
            by_category: {
                [key: string]: number;
            };
            /** By Priority */
            by_priority: {
                [key: string]: number;
            };
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Cache Age Seconds */
            cache_age_seconds: number | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Total */
            total: number;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "open" | "in_progress" | "resolved" | "rejected";
        /** StatusUpdate */
        StatusUpdate: {
            /** Note */
            note?: string | null;
            status: components["schemas"]["Status"];
        };
        /** TriageOutcome */
        TriageOutcome: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Cached */
            cached: boolean;
            /**
             * Complaint Id
             * Format: uuid
             */
            complaint_id: string;
            /** Error Class */
            error_class?: string | null;
            /** Fallback */
            fallback: boolean;
            /** Latency Ms */
            latency_ms: number;
            provider: components["schemas"]["TriagedBy"];
        };
        /**
         * TriagedBy
         * @enum {string}
         */
        TriagedBy: "llm:groq" | "llm:gemini" | "llm:ollama" | "rules" | "rules:fallback" | "simulated";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_complaints: {
        parameters: {
            query?: {
                category?: components["schemas"]["Category"][] | null;
                priority?: components["schemas"]["Priority"][] | null;
                status?: components["schemas"]["Status"][] | null;
                page?: number;
                page_size?: number;
                sort?: "created_at" | "-created_at" | "priority" | "-priority";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintPage"];
                };
            };
            /** @description Validation failed — field-level errors in `error.fields` */
            400: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_complaint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    /** @description /api/complaints/{id} */
                    Location?: string;
                    "X-RateLimit-Limit"?: number;
                    "X-RateLimit-Remaining"?: number;
                    "X-RateLimit-Reset"?: number;
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintOut"];
                };
            };
            /** @description Validation failed — field-level errors in `error.fields` */
            400: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    /** @description Integer seconds until the rate-limit window resets */
                    "Retry-After"?: number;
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_complaint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_complaint_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintOut"];
                };
            };
            /** @description Validation failed — field-level errors in `error.fields` */
            400: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid status transition — `error.details` names `from` and `to` */
            409: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersOut"];
                };
            };
        };
    };
    get_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    "X-Cache"?: "HIT" | "MISS";
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
            /** @description A dependency is unreachable — `error.details.failed` names it */
            503: {
                headers: {
                    /** @description Echoed from the request, or generated (UUIDv4) if absent/invalid */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
