"""initial: complaints table, native enums, indexes, updated_at trigger

Revision ID: 0001
Revises:
Create Date: 2026-09-24

Written by hand, not autogenerated — autogenerate does not get native PG enums, DESC
indexes, or triggers right (`05-DATA-LAYER.md §3.2`). Verify with
`alembic revision --autogenerate` producing an empty diff after this lands.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

from alembic import op
from app.domain.limits import CONTACT_MAX, LOCATION_MAX, SUMMARY_MAX

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        "CREATE TYPE category_enum AS ENUM "
        "('water','electricity','sanitation','roads','streetlights','other')"
    )
    op.execute("CREATE TYPE priority_enum AS ENUM ('high','normal','low')")
    op.execute("CREATE TYPE status_enum AS ENUM ('open','in_progress','resolved','rejected')")
    op.execute(
        "CREATE TYPE triaged_by_enum AS ENUM "
        "('llm:groq','llm:gemini','llm:ollama','rules','rules:fallback','simulated')"
    )

    op.create_table(
        "complaints",
        sa.Column(
            "id",
            pg.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=LOCATION_MAX), nullable=False),
        sa.Column("reporter_contact", sa.String(length=CONTACT_MAX), nullable=True),
        sa.Column(
            "category",
            pg.ENUM(name="category_enum", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "priority",
            pg.ENUM(name="priority_enum", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            pg.ENUM(name="status_enum", create_type=False),
            nullable=False,
            server_default=sa.text("'open'::status_enum"),
        ),
        sa.Column("ai_summary", sa.String(length=SUMMARY_MAX), nullable=True),
        sa.Column(
            "triaged_by",
            pg.ENUM(name="triaged_by_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("triage_latency_ms", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("triage_confidence", sa.Numeric(3, 2), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint("char_length(text) BETWEEN 10 AND 2000", name="ck_complaints_text_len"),
        sa.CheckConstraint(
            "char_length(location) BETWEEN 3 AND 200", name="ck_complaints_location_len"
        ),
        sa.CheckConstraint(
            "reporter_contact IS NULL OR char_length(reporter_contact) "
            f"BETWEEN 3 AND {CONTACT_MAX}",
            name="ck_complaints_contact_len",
        ),
        sa.CheckConstraint(
            f"ai_summary IS NULL OR char_length(ai_summary) <= {SUMMARY_MAX}",
            name="ck_complaints_summary_len",
        ),
        sa.CheckConstraint("triage_latency_ms >= 0", name="ck_complaints_latency_nonneg"),
        sa.CheckConstraint(
            "triage_confidence IS NULL OR (triage_confidence >= 0 AND triage_confidence <= 1)",
            name="ck_complaints_confidence_range",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_complaints"),
    )
    op.create_index(
        "ix_complaints_status_priority", "complaints", ["status", "priority"], unique=False
    )
    op.execute("CREATE INDEX ix_complaints_created_at ON complaints (created_at DESC)")

    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN NEW.updated_at = now(); RETURN NEW; END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_complaints_updated_at BEFORE UPDATE ON complaints
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_complaints_updated_at ON complaints")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.drop_index("ix_complaints_created_at", table_name="complaints")
    op.drop_index("ix_complaints_status_priority", table_name="complaints")
    op.drop_table("complaints")
    for t in ("triaged_by_enum", "status_enum", "priority_enum", "category_enum"):
        op.execute(f"DROP TYPE IF EXISTS {t}")
