// OpenTelemetry browser tracing bonus (+2, `10-OBSERVABILITY.md §6`). Off unless
// runtimeConfig().tracingEnabled is true (window.__CIVICPULSE__, generated by
// docker-entrypoint.d/10-config.sh) — mirrors the backend's own opt-in posture
// (app/tracing.py, off unless OTEL_EXPORTER_OTLP_ENDPOINT is set) so a plain dev/CI run never
// pays the SDK's setup cost or tries to reach a collector that isn't there.
//
// Instruments `fetch` only — every real network call this SPA makes goes through fetch
// (api/client.ts), so this is the one call site that needs auto-instrumentation, not every DOM
// event. `context-zone` (Zone.js-based context propagation) is required for the fetch
// instrumentation to correctly associate a request with the span that was active when it was
// issued; without it, concurrent requests can attribute their span to the wrong trace.
import { ZoneContextManager } from "@opentelemetry/context-zone";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";
import { FetchInstrumentation } from "@opentelemetry/instrumentation-fetch";
import { resourceFromAttributes } from "@opentelemetry/resources";
import { BatchSpanProcessor, WebTracerProvider } from "@opentelemetry/sdk-trace-web";

import { runtimeConfig } from "../api/config";

/** Call once, at app startup, before anything issues a fetch. No-ops if tracing is disabled. */
export function setupTracing(): void {
  const { tracingEnabled } = runtimeConfig();
  if (!tracingEnabled) return;

  const provider = new WebTracerProvider({
    resource: resourceFromAttributes({ "service.name": "civicpulse-frontend" }),
    spanProcessors: [
      new BatchSpanProcessor(new OTLPTraceExporter({ url: "/v1/traces" })),
      // Same-origin `/v1/traces`, proxied by nginx to jaeger — never a direct cross-origin
      // browser call to the collector, same "no API URL in the bundle" posture as api/config.ts.
    ],
  });
  provider.register({ contextManager: new ZoneContextManager() });

  new FetchInstrumentation({
    // Only propagate `traceparent` to same-origin requests — this SPA never calls a
    // third-party API directly (ADR-0002), but an explicit allow-list is the correct default
    // regardless: a trace header is metadata about OUR system, not something to hand to an
    // arbitrary origin a future change might introduce a fetch to.
    propagateTraceHeaderCorsUrls: [window.location.origin],
  }).enable();
}
